//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sportmen
    {
        public int Id { get; set; }
        public string Surname { get; set; }
        public int countryId { get; set; }
        public int sportId { get; set; }
        public int result { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Sport Sport { get; set; }
    }
}
