//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorClient.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.ICalculatorContract")]
    public interface ICalculatorContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorContract/Plus", ReplyAction="http://tempuri.org/ICalculatorContract/PlusResponse")]
        double Plus(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorContract/Plus", ReplyAction="http://tempuri.org/ICalculatorContract/PlusResponse")]
        System.Threading.Tasks.Task<double> PlusAsync(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorContract/Sqr", ReplyAction="http://tempuri.org/ICalculatorContract/SqrResponse")]
        double Sqr(double x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorContract/Sqr", ReplyAction="http://tempuri.org/ICalculatorContract/SqrResponse")]
        System.Threading.Tasks.Task<double> SqrAsync(double x);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculatorContractChannel : CalculatorClient.ServiceReference.ICalculatorContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorContractClient : System.ServiceModel.ClientBase<CalculatorClient.ServiceReference.ICalculatorContract>, CalculatorClient.ServiceReference.ICalculatorContract {
        
        public CalculatorContractClient() {
        }
        
        public CalculatorContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Plus(double x, double y) {
            return base.Channel.Plus(x, y);
        }
        
        public System.Threading.Tasks.Task<double> PlusAsync(double x, double y) {
            return base.Channel.PlusAsync(x, y);
        }
        
        public double Sqr(double x) {
            return base.Channel.Sqr(x);
        }
        
        public System.Threading.Tasks.Task<double> SqrAsync(double x) {
            return base.Channel.SqrAsync(x);
        }
    }
}
