//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.ICalculateContract")]
    public interface ICalculateContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculateContract/Plus", ReplyAction="http://tempuri.org/ICalculateContract/PlusResponse")]
        double Plus(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculateContract/Plus", ReplyAction="http://tempuri.org/ICalculateContract/PlusResponse")]
        System.Threading.Tasks.Task<double> PlusAsync(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculateContract/Sqr", ReplyAction="http://tempuri.org/ICalculateContract/SqrResponse")]
        double Sqr(double x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculateContract/Sqr", ReplyAction="http://tempuri.org/ICalculateContract/SqrResponse")]
        System.Threading.Tasks.Task<double> SqrAsync(double x);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculateContractChannel : Client.ServiceReference.ICalculateContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculateContractClient : System.ServiceModel.ClientBase<Client.ServiceReference.ICalculateContract>, Client.ServiceReference.ICalculateContract {
        
        public CalculateContractClient() {
        }
        
        public CalculateContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculateContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculateContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculateContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Plus(double x, double y) {
            return base.Channel.Plus(x, y);
        }
        
        public System.Threading.Tasks.Task<double> PlusAsync(double x, double y) {
            return base.Channel.PlusAsync(x, y);
        }
        
        public double Sqr(double x) {
            return base.Channel.Sqr(x);
        }
        
        public System.Threading.Tasks.Task<double> SqrAsync(double x) {
            return base.Channel.SqrAsync(x);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IDopContract")]
    public interface IDopContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDopContract/SinXCosY", ReplyAction="http://tempuri.org/IDopContract/SinXCosYResponse")]
        double SinXCosY(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDopContract/SinXCosY", ReplyAction="http://tempuri.org/IDopContract/SinXCosYResponse")]
        System.Threading.Tasks.Task<double> SinXCosYAsync(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDopContract/TexX", ReplyAction="http://tempuri.org/IDopContract/TexXResponse")]
        double TexX(double x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDopContract/TexX", ReplyAction="http://tempuri.org/IDopContract/TexXResponse")]
        System.Threading.Tasks.Task<double> TexXAsync(double x);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDopContractChannel : Client.ServiceReference.IDopContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DopContractClient : System.ServiceModel.ClientBase<Client.ServiceReference.IDopContract>, Client.ServiceReference.IDopContract {
        
        public DopContractClient() {
        }
        
        public DopContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DopContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DopContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DopContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double SinXCosY(double x, double y) {
            return base.Channel.SinXCosY(x, y);
        }
        
        public System.Threading.Tasks.Task<double> SinXCosYAsync(double x, double y) {
            return base.Channel.SinXCosYAsync(x, y);
        }
        
        public double TexX(double x) {
            return base.Channel.TexX(x);
        }
        
        public System.Threading.Tasks.Task<double> TexXAsync(double x) {
            return base.Channel.TexXAsync(x);
        }
    }
}
