//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankClient.BankServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BankServiceReference.IBankService", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IBankService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/ToDeposit", ReplyAction="http://tempuri.org/IBankService/ToDepositResponse")]
        void ToDeposit(decimal sum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/ToDeposit", ReplyAction="http://tempuri.org/IBankService/ToDepositResponse")]
        System.Threading.Tasks.Task ToDepositAsync(decimal sum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/GetBalance", ReplyAction="http://tempuri.org/IBankService/GetBalanceResponse")]
        decimal GetBalance();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/GetBalance", ReplyAction="http://tempuri.org/IBankService/GetBalanceResponse")]
        System.Threading.Tasks.Task<decimal> GetBalanceAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBankServiceChannel : BankClient.BankServiceReference.IBankService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankServiceClient : System.ServiceModel.ClientBase<BankClient.BankServiceReference.IBankService>, BankClient.BankServiceReference.IBankService {
        
        public BankServiceClient() {
        }
        
        public BankServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ToDeposit(decimal sum) {
            base.Channel.ToDeposit(sum);
        }
        
        public System.Threading.Tasks.Task ToDepositAsync(decimal sum) {
            return base.Channel.ToDepositAsync(sum);
        }
        
        public decimal GetBalance() {
            return base.Channel.GetBalance();
        }
        
        public System.Threading.Tasks.Task<decimal> GetBalanceAsync() {
            return base.Channel.GetBalanceAsync();
        }
    }
}
